runtime: python310
service: default

instance_class: F2

beta_settings:
  cloud_sql_instances: "backend-430606:us-central1:ebikesbackend"

env_variables:
  OPENAI_API_KEY: "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"
  GOOGLE_API_KEY: "AIzaSyCN-0aWhXvbLH4e62-UQWLp2eNKA8dP--4"
  GOOGLE_API_KEY_DP: "AIzaSyAmUpECvhnqC_g60Gg4olq4wWYzhPsP8t4"
  TWILIO_ACCOUNT_SID: "AC31cba00f3422400832bc11d4c14b1417"
  TWILIO_AUTH_TOKEN: "404f984b46a551c7f19c294def03d410"