runtime: python310
service: default

instance_class: F2

beta_settings:
  cloud_sql_instances: "backend-430606:us-central1:ebikesbackend"

env_variables:
  OKY: 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
  GOKY: AIzaSyCN-0aWhXvbLH4e62-UQWLp2eNKA8dP--4
  GOKY: AIzaSyAmUpECvhnqC_g60Gg4olq4wWYzhPsP8t4
  TWIID: AC31cba00f3422400832bc11d4c14b1417
  TWIKEN:"404f984b46a551c7f19c294def03d410
