# Generated by Django 5.0.6 on 2024-08-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EBApi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
