# Generated by Django 5.0.6 on 2024-07-18 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EBApi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="driver",
            new_name="rider",
        ),
    ]
