# Generated by Django 5.0.6 on 2024-07-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EBApi", "0002_rename_driver_order_rider"),
    ]

    operations = [
        migrations.AddField(
            model_name="distancerecord",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
