# Generated by Django 5.0.6 on 2024-09-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EBApi", "0002_order_order_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("active", "Active"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
