# Generated by Django 5.0.6 on 2024-10-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EBApi", "0003_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=255)),
                ("conversation_history", models.TextField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RiderMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rider_id", models.CharField(max_length=255)),
                ("conversation_history", models.TextField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
