# Generated by Django 5.0.6 on 2024-11-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EBApi", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="distance",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
